# Generated by Django 5.0.2 on 2024-02-12 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuerry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=20)),
                ('item_title', models.CharField(max_length=150)),
                ('item_promoted', models.CharField(max_length=20)),
                ('item_ean', models.CharField(max_length=20)),
                ('item_price', models.FloatField()),
                ('seller_id', models.CharField(max_length=20)),
                ('seller_name', models.CharField(max_length=20)),
                ('seller_url', models.CharField(max_length=25)),
                ('seller_feedback', models.CharField(max_length=10)),
                ('seller_supperSeller', models.CharField(max_length=10)),
                ('item_best_price_guarantee', models.CharField(max_length=20)),
                ('item_rating', models.CharField(max_length=10)),
                ('item_rating_count', models.CharField(max_length=10)),
                ('item_isSmart', models.CharField(max_length=10)),
                ('item_offers_count', models.CharField(max_length=5)),
                ('item_units_sold', models.CharField(max_length=20)),
                ('item_sales_value', models.CharField(max_length=20)),
                ('item_url', models.CharField(max_length=100)),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_apps.searchquerry')),
            ],
        ),
    ]
