# Generated by Django 5.0.2 on 2024-02-14 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_apps', '0004_searchquery_delete_searchquerry'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='search_query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_apps.searchquery'),
        ),
    ]
